### ISSUE TITLE
Display the date & time disabled in the Reason field for bots disabled on BASIL due to being too long disabled on SSCAIT

### ISSUE THREAD

**Issue by chriscoxe** [basil-ladder/basil#24]
Display the date & time disabled in the Reason field for bots disabled on BASIL due to being too long disabled on SSCAIT.

E.g. if the bot named "Middle School Strats" is currently disabled on BASIL and it became disabled on SSCAIT on 2018.12.30 and this is the reason why (or part of the reason why) it become disabled on BASIL at 2019.01.06 03:02:03 am  then the "Reason" field for it in the "Disabled bots" table on the page http://basil.bytekeeper.org/ranking.html could say something like "Disabled on BASIL at 2019.01.06 03:02:03 am due to being disabled on SSCAIT on 2018.12.30".  "Date Disabled on BASIL" could even be a separate column as "2019.01.06 03:02:03 am" (the Reason field could just say "Disabled on SSCAIT on 2018.12.30").

Note: as far as I know, BASIL only checks the status of the SSCAIT bots periodically (I gather it's about every 6 hours currently).  The date disabled on SSCAIT should probably be the date (& maybe time) that BASIL detected that it became disabled on SSCAIT.  As far as I know, the "Updated" date & time field on SSCAIT is not necessarily the date it was disabled - in some cases it might be an earlier date which is the date the bot's files were last updated (only the enabled/disabled flag was changed, not the "Updated" field value).  This might happen if an SSCAIT administrator manually disables a bot by changing the enabled/disabled flag from Enabled to Disabled without changing the bot's actual files.

**Comment by chriscoxe** [comment]
From discussion on Discord, it seems BASIL is currently just looking at whether a bot is currently disabled on SSCAIT and its "Updated" date/time value on SSCAIT, rather than tracking how long SSCAIT bots have been disabled on SSCAIT.  So if you want to implement this, BASIL would need to start tracking it.  Tracking it would avoid the issue where SSCAIT admins disable some bots just before the SSCAIT end-of-year tourney which I gather caused BASIL to automatically immediately disable the following bots as soon as they became disabled on SSCAIT (rather than waiting 65 days): tscmoor, tscmoo, tscmooz, skyFORKnet, Stone, Zia bot, PotatoMasher, UITtest2, Middle School Strats, DaQin, Oh Fish, Fresh Meat

**Comment by MicroDK** [comment]
Yes... some bots were enambled by admin after SSCAIT tournament but are still disabled on Basil... this should be fixed so we get out favorite bots playing again. :)

**Comment by Bytekeeper** [comment]
Yes. The problem was that the admin enabled them which didn't change the last updated date. Which is what BASIL basically used up to now. There's no enabled since so BASIL will have to find that out by polling.

**Comment by Bytekeeper** [comment]
Ok, this is now obsolete as BASIL no longer will disable bots if they are disabled on SSCAIT.
