### ISSUE TITLE
Close Opposition Graph shows an incorrect curve

### ISSUE THREAD

**Issue by Cmccrave** [basil-ladder/basil#43]
It appears that the plotted points use a percentage that is calculated on the previous point.
Example, McRave vs Dragon:
![image](https://user-images.githubusercontent.com/25108498/62875868-cc2aad80-bcf1-11e9-9317-145e461c8503.png)

Starting at the point on July 23:
I am 1-4, but the curve shows 0%.
Then 1-5, curve shows 20%. This is actually 1/5 (previous point).
Then 2-5, curve shows 16.67%. This is actually 1/6 (previous point).

This looks like it's calculating the previous percentage rather than current.

**Comment by Bytekeeper** [comment]
Fixed with ed5c9e249366dd248c2202fdb7da7becc0aa8d60.
