### ISSUE TITLE
Request for Random Replay Selection

### ISSUE THREAD

**Issue by NiteKat** [basil-ladder/basil#47]
SSCAIT implemented at the bottom of their bots and results page a section which grabs 10 random replays from the last 7 days. It displays the ELO difference between the opponents, who the two players were (including race), date/time, and a link to the replay (with OpenBW link too). This random game list is updated either every minute or 5 minutes (I forget which), but you have to refresh to see the new list when it is generated.

This issue is to request something similar for BASIL. Having this type of random selection available helps with making casts for SSCAIT, especially with knowing the ELO difference (generally closer ELO is going to produce better games for casting).  BASIL also has some bots active now that SSCAIT does not, so it would be nice to source games from BASIL in a similar fashion to sourcing them from SSCAIT.

**Comment by Bytekeeper** [comment]
@NiteKat I think is ok for now. Feel free to open a new ticket if it's lacking.
