### ISSUE TITLE
On ranking page, "Rank" header cell floats when scrolling to the right

### ISSUE THREAD

**Issue by bmnielsen** [basil-ladder/basil#52]
Steps to reproduce:

1. Open the ranking page
2. Reduce the page width so the page can be scrolled horizontally
3. Scroll to the right and observe that the "Rank" header cell sticks to the left side of the screen so it floats over the other header cells

Seems to be caused by this styling: https://github.com/basil-ladder/basil/blob/gh-pages/_sass/basil.scss#L142-L145

**Comment by Bytekeeper** [comment]
Yeah, the intention was to lock the "bot" column of the crosstable in place. Moved the CSS around a bit.
